### ISSUE TITLE
Is there any function to reload the waterfall?

### ISSUE THREAD

**Issue by lucky-leung** [bingdian/waterfall#14]
Is there any function to reload the waterfall?
翻页时当新数据要重新刷新是要怎么做？是否有个reload的方法能调用？
方便留下qq等通信方式吗？

**Comment by Mavinbin** [comment]
其实作者的这个插件还是可以实现翻页无刷新的...只是要在触发重新调用数据的地方要先清空之前的数据，然后用option方法重新配置动态的参数
