### ISSUE TITLE
数据完成最后拍能加一个对齐功能就更好了

### ISSUE THREAD

**Issue by 63490794** [bingdian/waterfall#19]
比如下面图片，我觉得在 有限下拉数据完成后显示分页 非常有用

![00](https://cloud.githubusercontent.com/assets/1973949/5370670/11696422-8061-11e4-88f1-0bf17fd25daa.jpg)

![00](https://cloud.githubusercontent.com/assets/1973949/5370664/fe4fdc22-8060-11e4-9dab-378a63701f6f.jpg)

**Comment by bingdian** [comment]
您好，感谢您的建议，暂时不考虑添加此功能。
