### ISSUE TITLE
callbacks 中的 renderData 无效

### ISSUE THREAD

**Issue by zhao-ji** [bingdian/waterfall#20]
renderData 的作用时间应该是在从path中得到地址，请求得到数据之后，在render之前吧？
现在重写callbacks的renderData发现无效，最终render出来的data还是从path中请求得到的，没有变化。

**Comment by glh1991** [comment]
服务器端返回结果为{}时，page仍然不断+1,不停的发起请求。如何解决

**Comment by fitoe** [comment]
数据到底了，还在不断请求。怎么解决？

**Comment by bingdian** [comment]
可以参考 http://wlog.cn/demo/waterfall/no-more-data.html， 使用 `pause` 有方法停止请求数据，`$('#container').waterfall('pause', callback);`

**Comment by fitoe** [comment]
没想到你在啊，刚刚解决了数据为0时无限加载。如果查询到0，服务器端返回“end”就可以了。

**Comment by fitoe** [comment]
数据加载出错以后，好像只能刷新页面才能解决。
