### ISSUE TITLE
底部出现的空白滚动条应该去掉

### ISSUE THREAD

**Issue by senntyou** [bingdian/waterfall#26]
![image](https://cloud.githubusercontent.com/assets/12265053/9079326/8cad148c-3b7b-11e5-9325-c2ae3e1fd449.png)

底部这个空白滚动条毫无意义，在
https://github.com/bingdian/waterfall/blob/master/build/waterfall.js#L186
```
$('body').css({
    overflow: 'scroll'
});
```
改成
```
$('body').css({
    overflow: 'auto'
});
```
就好了，
如何？

**Comment by bingdian** [comment]
问题已修复，谢谢
