### ISSUE TITLE
can I add a click event to the img element?

### ISSUE THREAD

**Issue by liangt** [bingdian/waterfall#29]
The js template is:

```
 {{#result}}
           <div class="item">
                <img class="thumbs" src="{{image}}" width="{{width}}" height="{{height}}" />
            </div>
{{/result}}
```

And I'm try to add a click event to the img element, part of my code is as following:

```
$(".thumbs").click(function(){
        alert('click');
 });
```

But, unfortunately, it doesn't work. I'm not good at js and can someone help me? thanks.

**Comment by wildish** [comment]
you should bind click events after the images have been created.

**Comment by RosApr** [comment]
冒泡
